[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd apps/api && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python API build complete'"]

[start]
cmd = "cd apps/api && uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
